In [1]:
println("Hello, World!")

Hello, World!


In [2]:
println("Hello"*" hi")

Hello hi


In [5]:
println("Hello"*" hi"^2)

Hello hi hi


In [6]:
println(("Hello"*" hi")^2)

Hello hiHello hi


In [7]:
!((true && true) || false)

false

In [8]:
5040/60

84.0

In [10]:
1.7^20

40642.3140664757

In [11]:
1.5^1.7^20

Inf

In [2]:
(2^2)^3 - 2^4

48

In [3]:
println("$(6*6)")

36


In [4]:
1 + 3 < 5 && 2^2 === 4.0

false

In [7]:
matrix = Array{Float64,2}(undef, 3, 3)

3×3 Array{Float64,2}:
 1.69251e-315  1.69248e-315  1.69249e-315
 1.69227e-315  1.69248e-315  1.69249e-315
 1.69248e-315  1.69227e-315  1.69185e-315

In [8]:
matrix[1,:]

3-element Array{Float64,1}:
 1.69251436e-315
 1.692477047e-315
 1.692487007e-315

In [9]:
a, b = 2, 3           
function f(x)  
  b = 5 
  a*x + b
end
f(7), b

(19, 3)

In [10]:
y(x) = x*x;

In [11]:
y(3)

9

In [1]:
?Help

search: schedule Channel hasfield @threadcall AbstractChannel searchsortedlast

Couldn't find Help
Perhaps you meant exp, HTML, chop, sech, less, Meta, Set, Text, Val, all or all!


No documentation found.

Binding `Help` does not exist.


In [2]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` followed by a newline. If `io` is not supplied, prints to [`stdout`](@ref).

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello, world")

julia> String(take!(io))
"Hello, world\n"
```


In [3]:
?syntax

search:

Couldn't find syntax
Perhaps you meant stat, minmax or @sync


No documentation found.

Binding `syntax` does not exist.


In [5]:
/gamma = 3

LoadError: syntax: "/" is not a unary operator

In [10]:
Array{String}(undef,2,1)

2×1 Array{String,2}:
 #undef
 #undef

### assignment : =
### equality : ==
### 
### A function that modifies the arguement has ! in the end.

In [11]:
?cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos sincosd const close



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
  0.291927  -0.708073
 -0.708073   0.291927
```


In [16]:
### Press tab to find funcitons and other latex symbols

In [13]:
γ


UndefVarError: UndefVarError: _gamma not defined

In [17]:
¥ = 4

4